### ISSUE TITLE
Found one high everity vulnerability

### ISSUE THREAD

**Issue by qinyihao** [eswar2001/cptime#6]
Hi there, when I ran `npm install`, there comes one warning:

> found 1 high severity vulnerability
>   run `npm audit fix` to fix them, or `npm audit` for details

Please fix that, thanks.

**Comment by eswar2001** [comment]
Thanks for pointing it out.  Issue resolved by updating the package versions with the following commands:
```
npm install -g npm-check-updates
ncu -u
npm install
```

Though `npm audit fix` works there aren't any breaking changes in the newer versions of dependencies and again thanks for pointing it out.
